version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: teknofile/tkf-docker-cacti
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t ${IMAGE_NAME}:latest .
      - run:
          name: Archive Docker Image
          command: docker save -o image.tar ${IMAGE_NAME}:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load Docker Image From Workspace
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker To Docker Hub
          command: |
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${CIRCLE_SHA1}
            docker push ${IMAGE_NAME}:latest
            docker push ${IMAGE_NAME}:${CIRCLE_SHA1}
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          context: DockerPublishInfo
          filters:
            branches:
              only: master
      - publish-latest:
          context: DockerPublishInfo
          requires:
            - build
          filters:
            branches:
              only: master
