#!/usr/bin/with-contenv bash

mkdir -p \
  /config/www/cacti \
  /var/www/localhost/cacti \
  /config/log/cacti 

# Install Cacti if necessary

if [ -f /cacti/cacti.tar.gz ]; then
  echo "New container detected, installing Cacti"
  tar xf /cacti/cacti.tar.gz -C /var/www/localhost/cacti --strip-components=1
  chown -R abc:abc /var/www/localhost/cacti
fi


echo "Setting permissions"
chown -R abc:abc /config
