#!/usr/bin/with-contenv bash

# make our folders
echo "** Making our folders"
mkdir -p \
	/config/{nginx/site-confs,www,log/nginx,keys,log/php,php} \
	/run \
    /run/php \
	/var/lib/nginx/tmp/client_body \
	/var/tmp/nginx

[[ -f /defaults/www.conf ]] && \
  cp /defaults/www.conf /etc/php/7.2/fpm/pool.d/

# copy config files
echo "** Copy default configurations into /config"
[[ ! -f /config/nginx/nginx.conf ]] && \
	cp /defaults/nginx.conf /config/nginx/nginx.conf
[[ ! -f /config/nginx/site-confs/default ]] && \
	cp /defaults/default /config/nginx/site-confs/default
#[[ $(find /config/www -type f | wc -l) -eq 0 ]] && \
#	cp /defaults/index.html /config/www/index.html

[[ ! -f /config/php/www2.conf ]] && \
  cp /defaults/www2.conf /config/php/www2.conf

sed -i "s#user = nobody.*#user = tkf#g" /etc/php/7.2/fpm/pool.d/www.conf
sed -i "s#group = nobody.*#group = tkf#g" /etc/php/7.2/fpm/pool.d/www.conf
# create override for www.conf if it doesn't exist
[[ ! -f /config/php/www2.conf ]] && \
	printf "; Edit this file to override www.conf and php-fpm.conf directives and restart the container\\n\\n; Pool name\\n[www]\\n\\n" > /config/php/www2.conf
# copy user www2.conf to image
cp /config/php/www2.conf /etc/php/7.2/fpm/pool.d/www2.conf

# permissions
chown -R tkf:tkf \
	/config \
	/var/lib/nginx \
	/var/tmp/nginx
chmod -R g+w \
	/config/{nginx,www}
chmod -R 644 /etc/logrotate.d
